name: Test

on:
  push:
    branches: ['**']
    tags-ignore: ['*']
  pull_request:

env:
  GODOT_VERSION: 4.3
  HOME: /github/home

jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        run: |
          mkdir -p "$HOME" "$HOME/.config" "$HOME/.local/share"
      - name: Install dependencies
        run: apt-get update && apt-get install -y git make
      - name: Run automated tests
        run: bash scripts/test.sh
